Election.create(year: 2019)
Group.create(name: "global", election: Election.last)
Group.create(name: "10A", election: Election.last)
Group.create(name: "10B", election: Election.last)
Voter.create(identification: 123, voted: 0, election: Election.last, group: Group.where(name: "10B").first)
Voter.create(identification: 456, voted: 0, election: Election.last, group: Group.where(name: "10B").first)
Voter.create(identification: 321, voted: 0, election: Election.last, group: Group.where(name: "10A").first)
Voter.create(identification: 654, voted: 0, election: Election.last, group: Group.where(name: "10A").first)
Position.create(name: "Personero", group: Group.where(name: "global").first)
Position.create(name: "Contralor", group: Group.where(name: "global").first)
Position.create(name: "Representante 10A", group: Group.where(name: "10A").first)
Position.create(name: "Representante 10B", group: Group.where(name: "10B").first)
Candidate.create(name: "Juana de Arco", election: Election.last, picture_url: "", position: Position.where(name: "Personero").first)
Candidate.create(name: "Partick", election: Election.last, picture_url: "", position: Position.where(name: "Representante 10A").first)
Candidate.create(name: "Esteban Nano", election: Election.last, picture_url: "", position: Position.where(name: "Representante 10A").first)
Candidate.create(name: "Juaquin Dorios", election: Election.last, picture_url: "", position: Position.where(name: "Representante 10B").first)
Candidate.create(name: "Contra Prohibir", election: Election.last, picture_url: "", position: Position.where(name: "Contralor").first)
